#!/bin/sh

echo 'Generating tags for perl ...'
ctags -f ~/.vim/tags/perl/cpan.tags --recurse --totals \
    --exclude=blib \
    --exclude=.svn \
    --exclude='*~' \
    --languages=Perl --langmap=Perl:+.t \
    /Library/Perl/5.8.8/


