#!/usr/bin/perl
use strict;
use warnings;
use ExtUtils::MakeMaker qw(prompt);
use File::Basename;
use File::Path;
use File::Spec;
use Text::Xslate;
use YAML;
use Config::Pit;

main();
exit;

sub main {
    my $config = initialize_config();
    -e $config->{workdir} || mkdir $config->{workdir}, 0777;
    my $module = get_module_name();

    my $dist_dir = _create_dist_dir($module);
    chdir $dist_dir;

    generate_sphinx_docs($module, $config);
    write_plugin_files( $module, $config );
}

sub get_module_name {
    my $module = shift @ARGV or die "Usage: $0 module\n";
    $module =~ s/-/::/g;
    return $module;
}

sub initialize_config {
    my $config = pit_get(
        "pysetup",
        require => {
            author  => "your username",
            email   => "your email",
            workdir => "$ENV{HOME}/tmp",
        }
    );

           $config->{author}
        || $config->{email}
        || $config->{workdir} || die("no settings");
    return $config;
}

sub write_plugin_files {
    my ( $module, $config ) = @_;

    my @template = YAML::Load( join '', <DATA> );
    my $vars = {
        module    => $module,
        config    => $config,
        localtime => scalar localtime
    };

    for my $tmpl (@template) {
        my $file = $tmpl->{file};
        $file =~ s/(\$\w+)/$1/eeg;
        write_file( $file, $tmpl->{template}, $vars );
        chmod oct( $tmpl->{chmod} ), $tmpl->{file} if $tmpl->{chmod};
    }

    init_git_repo($module);
}

sub _create_dist_dir {
    my $module = shift;
    my $dist   = "python-${module}";
    mkdir $dist, 0777;
    $dist;
}

sub generate_sphinx_docs {
    my ($module, $config) = @_;
    system "cat <<EOF | sphinx-quickstart
docs
n
_
$module
$config->{author}
0.01
0.01
.rst
index
y
y
y
y
y
y
y
y
y
y
y
y
EOF
";
}

sub init_git_repo {
    my $module = shift;
    !system 'git init'                       or die $?;
    !system 'git add *.*'                    or die $?;
    !system 'git add README.rst'             or die $?;
    !system 'git add CHANGES.rst'            or die $?;
    !system 'git add LICENSE.txt'            or die $?;
    !system 'git add .gitignore'             or die $?;
    !system 'git add Makefile'               or die $?;
    !system "git add ${module}"              or die $?;
    !system "git add docs"                   or die $?;
    !system 'git commit -m "initial commit"' or die $?;
}

sub write_file {
    my ( $path, $template, $vars ) = @_;

    if ( -e $path ) {
        my $ans = prompt( "$path exists. Override? [yN] ", 'n' );
        return if $ans !~ /[Yy]/;
    }

    my $dir = File::Basename::dirname($path);
    unless ( -e $dir ) {
        warn "Creating directory $dir\n";
        File::Path::mkpath( $dir, 1, 0777 );
    }

    my $tt = Text::Xslate->new( syntax => 'TTerse' );
    my $content = $tt->render_string( $template, $vars );

    warn "Creating $path\n";
    open my $out, ">", $path or die "$path: $!";
    print $out $content;
    close $out;
}

=pod

=cut

__DATA__
---
file: $module/__init__.py
template: |
  # -*- coding: utf-8 -*-

  """
      [% module %] is the .
  
      It provides .
  
      :copyright: (c) 2011 by [% config.author %].
      :license: BSD, see LICENSE for more details.
  """

---
file: $module/tests/__init__.py
template: |
  # -*- coding: utf-8 -*-
  """
  """

---
file: $module/tests/test_pyflakes.py
template: |
  # -*- coding: utf-8 -*-
  
  import compiler
  import os
  import sys
  
  import pyflakes.checker
  
  
  def check(codeString, filename):
      try:
          tree = compiler.parse(codeString)
      except (SyntaxError, IndentationError):
          value = sys.exc_info()[1]
          (lineno, offset, line) = value[1][1:]
          if line.endswith("\n"):
              line = line[:-1]
          raise AssertionError(
              "could not compile %s:%d: %s" % (filename[9:], lineno, line))
      else:
          w = pyflakes.checker.Checker(tree, filename)
          w.messages.sort(lambda a, b: cmp(a.lineno, b.lineno))
          return list(w.messages)
      return []
  
  
  def check_path(filename):
      if os.path.exists(filename):
          return check(file(filename).read(), filename)
      return []
  
  
  def check_subdirectory(directory):
      warnings = []
      for dirpath, dirnames, filenames in os.walk(directory):
          for filename in filenames:
              if filename.endswith('.py'):
                  warnings += check_path(os.path.join(dirpath, filename))
      return warnings
  
  
  def test_pyflakes():
      test_dir = os.path.dirname(__file__)
      lib_dir = os.path.join(test_dir, '..')
      warnings = check_subdirectory(lib_dir)
      if warnings:
          for warning in warnings:
              print str(warning)[9:]
          assert warnings == 0, "%d warnings" % len(warnings)
  
---
file: $module/tests/test_pep8.py
template: |
  # -*- coding: utf-8 -*-
  
  import os
  import pep8
  
  CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
  BASE_DIR = os.path.dirname(CURRENT_DIR)

  
  def test_pep8():
      arglist = [
          '--statistics',
          '--filename=*.py',
          '--show-source',
          '--repeat',
          #'--show-pep8',
          #'-qq',
          #'-v',
          BASE_DIR,
      ]
  
      options, args = pep8.process_options(arglist)
      runner = pep8.input_file
  
      for path in args:
          if os.path.isdir(path):
              pep8.input_dir(path, runner=runner)
          elif not pep8.excluded(path):
              options.counters['files'] += 1
              runner(path)
  
      pep8.print_statistics()
      errors = pep8.get_count('E')
      warnings = pep8.get_count('W')
      message = 'pep8: %d errors / %d warnings' % (errors, warnings)
      print message
      assert errors + warnings == 0, message
  
---
file: docs/.gitignore
template: |
  _themes
  _build

---
file: scripts/release.py
template: |
  #!/usr/bin/env python
  # -*- coding: utf-8 -*-
  """
      release
      ~~~~~~~
  
      Helper script that performs a release.
  
      :copyright: (c) 2011 by Dann
      :license: BSD, see LICENSE.txt for more details.
  """
  import sys
  import os
  import re
  from subprocess import Popen, PIPE
  
  
  def get_release_version():
      with open('CHANGES.rst') as f:
          lineiter = iter(f)
          for line in lineiter:
              match = re.search('^Version\s+(.*)', line.strip())
              if match is None:
                  continue
              version = match.group(1).strip()
              return version
  
  
  def check_release(version):
      log_info("Checking release: %s", version)
      check_is_repo_clean()
      check_version_isnt_in_tags(version)
  
  
  def check_version_isnt_in_tags(version):
      tags = get_git_tags()
  
      if version in tags:
          log_fail('Version "%s" is already tagged', version)
  
  
  def check_is_repo_clean():
      if not is_git_clean():
          log_fail('You have uncommitted changes in git')
  
  
  def get_git_tags():
      return set(Popen(['git', 'tag'], stdout=PIPE).communicate()[0].splitlines())
  

  def is_git_clean():
      return Popen(['git', 'diff', '--quiet']).wait() == 0
  
  
  def make_git_commit(message, *args):
      message = message % args
      Popen(['git', 'commit', '-am', message]).wait()
  
  
  def make_git_tag(tag):
      log_info('Tagging "%s"', tag)
      Popen(['git', 'tag', tag]).wait()
  
  
  def build_and_upload():
      log_info('Building and uploading to PyPI ...');
      Popen([sys.executable, 'setup.py', 'release', 'sdist', 'upload']).wait()
  
  
  def log_fail(message, *args):
      print >> sys.stderr, 'Error:', message % args
      sys.exit(1)
  
  
  def log_info(message, *args):
      print >> sys.stderr, message % args
  
  
  def main():
      os.chdir(os.path.join(os.path.dirname(__file__), '..'))
  
      version = get_release_version()
      if version is None:
          log_fail('Could not get the version from changelog.')
  
      log_info('Releasing %s', version)
  
      check_release(version)
      make_git_commit('Bump version number to %s', version)
      make_git_tag(version)
      build_and_upload()
  
  
  if __name__ == '__main__':
      main()

---
file: CHANGES.rst
template: |
  Revision history for Python extension [% module %]
  ==================================================

  Version 0.01 
  ------------
  Released on [% localtime %]

  - initial release

---
file: LICENSE.txt
template: |
  Copyright (c) 2012, [% config.author %]
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
      * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.
      * Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
      * Neither the name of the [% config.author %] nor the
        names of its contributors may be used to endorse or promote products
        derived from this software without specific prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

---
file: README.rst
template: |

  This is Python module [% module %].

  INSTALLATION
  -------

  [% module %] installation is straightforward. If your pip is set up,
  you should just be able to do

      % pip install [% module %]

  DOCUMENTATION
  -------

  [% module %] documentation is available . So you can do:

      % pydoc [% module %]

  to read the documentation online with your favorite pager.

  [% config.author %]

---
file: setup.py
template: |
  import os
  import sys
  
  from setuptools import setup, find_packages
  
  if sys.version_info[:2] < (2, 6):
      raise RuntimeError('Requires Python 2.6 or better')
  
  here = os.path.abspath(os.path.dirname(__file__))
  try:
      README = open(os.path.join(here, 'README.rst')).read()
      CHANGES = open(os.path.join(here, 'CHANGES.rst')).read()
  except IOError:
      README = CHANGES = ''
  
  install_requires=[
      'setuptools',
      ]
  
  tests_require = install_requires + [
      'virtualenv',
      'Sphinx',
      'docutils',
      ]
  
  setup(name='[% module %]',
        version='0.01',
        description=('[% module %] project'),
        long_description=README + '\n\n' +  CHANGES,
        classifiers=[
          "Intended Audience :: Developers",
          "Programming Language :: Python",
          "Programming Language :: Python :: 2.6",
          "Programming Language :: Python :: 2.7",
          "Programming Language :: Python :: Implementation :: CPython",
          "Programming Language :: Python :: Implementation :: PyPy",
          "License :: OSI Approved :: BSD License",
          'Topic :: Software Development :: Libraries :: Python Modules'
          ],
        keywords='',
        author="[% config.author %]",
        author_email="[% config.email %] ",
        url="http://github.com/dann/python-[% module %]",
        license="New BSD License",
        packages=find_packages(),
        include_package_data=True,
        zip_safe=False,
        install_requires = install_requires,
        tests_require = tests_require,
        test_suite="[% module %].tests",
        entry_points = """\
        """
        )

---
file: setup.cfg 
template: |
  [egg_info]
  tag_build = dev
  tag_date = true
  
  [aliases]
  release = egg_info -RDb ''

---
file: .gitignore
template: |
  *.egg
  *.egg-info
  *.pyc
  *$py.class
  *.pt.py
  *.txt.py
  *~
  .coverage
  .tox/
  nosetests.xml
  [% module %]/coverage.xml
  build/
  dist/
  bin/
  lib/
  include/
  distribute-*.tar.gz
  bookenv/
  jyenv/
  pypyenv/
  env*/

---
file: tox.ini 
template: |
  [tox]
  envlist=py25,py26,py27
  
  [testenv]
  commands=make test

---
file: Manifest.in 
template: |
  include Makefile CHANGES.txt LICENSE.txt
  recursive-include tests *
  recursive-include examples *
  recursive-include docs *
  recursive-exclude docs *.pyc
  recursive-exclude docs *.pyo
  recursive-exclude tests *.pyc
  recursive-exclude tests *.pyo
  recursive-exclude examples *.pyc
  recursive-exclude examples *.pyo
  prune docs/_build
  prune docs/_themes/.git

---
file: Makefile 
template: |
  .PHONY: clean test docs dist
  
  all: clean test
  
  test:
  	python setup.py test 
  
  tox-test:
  	PYTHONDONTWRITEBYTECODE= tox
  
  clean:
  	find . -name '*.pyc' -exec rm -f {} +
  	find . -name '*.pyo' -exec rm -f {} +
  	find . -name '*~' -exec rm -f {} +
  	python setup.py clean
  
  docs:
  	$(MAKE) -C docs html

  dist:
  	python setup.py sdist

  install:
  	python setup.py install
